// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Logging;

namespace Microsoft.EntityFrameworkCore.Taos.Internal
{
    /// <summary>
    ///		This API supports the Entity Framework Core infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public static class TaosStrings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.EntityFrameworkCore.Taos.Properties.TaosStrings", typeof(TaosStrings).GetTypeInfo().Assembly);

        /// <summary>
        ///     Taos does not support this migration operation ('{operation}'). For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
        /// </summary>
        public static string InvalidMigrationOperation([CanBeNull] object operation)
            => string.Format(
                GetString("InvalidMigrationOperation", nameof(operation)),
                operation);

        /// <summary>
        ///     Generating idempotent scripts for migration is not currently supported by Taos. For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
        /// </summary>
        public static string MigrationScriptGenerationNotSupported
            => GetString("MigrationScriptGenerationNotSupported");

        /// <summary>
        ///     The entity type '{entityType}' is configured to use schema '{schema}'. Taos does not support schemas. This configuration will be ignored by the Taos provider.
        /// </summary>
        public static readonly EventDefinition<string, string> LogSchemaConfigured
            = new EventDefinition<string, string>(
                TaosEventId.SchemaConfiguredWarning,
                LogLevel.Warning,
                "TaosEventId.SchemaConfiguredWarning",
                LoggerMessage.Define<string, string>(
                    LogLevel.Warning,
                    TaosEventId.SchemaConfiguredWarning,
                    _resourceManager.GetString("LogSchemaConfigured")));

        /// <summary>
        ///     The model was configured with the database sequence '{sequence}'. Taos does not support sequences.
        /// </summary>
        public static readonly EventDefinition<string> LogSequenceConfigured
            = new EventDefinition<string>(
                TaosEventId.SequenceConfiguredWarning,
                LogLevel.Warning,
                "TaosEventId.SequenceConfiguredWarning",
                LoggerMessage.Define<string>(
                    LogLevel.Warning,
                    TaosEventId.SequenceConfiguredWarning,
                    _resourceManager.GetString("LogSequenceConfigured")));

        /// <summary>
        ///     Taos does not support sequences. For more information, see http://go.microsoft.com/fwlink/?LinkId=723262.
        /// </summary>
        public static string SequencesNotSupported
            => GetString("SequencesNotSupported");

        /// <summary>
        ///     Taos doesn't support schemas. The specified schema selection arguments will be ignored.
        /// </summary>
        public static readonly EventDefinition LogUsingSchemaSelectionsWarning
            = new EventDefinition(
                TaosEventId.SchemasNotSupportedWarning,
                LogLevel.Warning,
                "TaosEventId.SchemasNotSupportedWarning",
                LoggerMessage.Define(
                    LogLevel.Warning,
                    TaosEventId.SchemasNotSupportedWarning,
                    _resourceManager.GetString("LogUsingSchemaSelectionsWarning")));

        /// <summary>
        ///     Found column on table: {tableName}, column name: {columnName}, data type: {dataType}, not nullable: {isNotNullable}, default value: {defaultValue}.
        /// </summary>
        public static readonly EventDefinition<string, string, string, bool, string> LogFoundColumn
            = new EventDefinition<string, string, string, bool, string>(
                TaosEventId.ColumnFound,
                LogLevel.Debug,
                "TaosEventId.ColumnFound",
                LoggerMessage.Define<string, string, string, bool, string>(
                    LogLevel.Debug,
                    TaosEventId.ColumnFound,
                    _resourceManager.GetString("LogFoundColumn")));

        /// <summary>
        ///     Found foreign key on table: {tableName}, id: {id}, principal table: {principalTableName}, delete action: {deleteAction}.
        /// </summary>
        public static readonly EventDefinition<string, long, string, string> LogFoundForeignKey
            = new EventDefinition<string, long, string, string>(
                TaosEventId.ForeignKeyFound,
                LogLevel.Debug,
                "TaosEventId.ForeignKeyFound",
                LoggerMessage.Define<string, long, string, string>(
                    LogLevel.Debug,
                    TaosEventId.ForeignKeyFound,
                    _resourceManager.GetString("LogFoundForeignKey")));

        /// <summary>
        ///     Could not scaffold the foreign key '{foreignKeyName}'. The referenced table could not be found. This most likely occurred because the referenced table was excluded from scaffolding.
        /// </summary>
        public static readonly EventDefinition<string> LogForeignKeyScaffoldErrorPrincipalTableNotFound
            = new EventDefinition<string>(
                TaosEventId.ForeignKeyReferencesMissingTableWarning,
                LogLevel.Warning,
                "TaosEventId.ForeignKeyReferencesMissingTableWarning",
                LoggerMessage.Define<string>(
                    LogLevel.Warning,
                    TaosEventId.ForeignKeyReferencesMissingTableWarning,
                    _resourceManager.GetString("LogForeignKeyScaffoldErrorPrincipalTableNotFound")));

        /// <summary>
        ///     Found table with name: {name}.
        /// </summary>
        public static readonly EventDefinition<string> LogFoundTable
            = new EventDefinition<string>(
                TaosEventId.TableFound,
                LogLevel.Debug,
                "TaosEventId.TableFound",
                LoggerMessage.Define<string>(
                    LogLevel.Debug,
                    TaosEventId.TableFound,
                    _resourceManager.GetString("LogFoundTable")));

        /// <summary>
        ///     Unable to find a table in the database matching the selected table {table}.
        /// </summary>
        public static readonly EventDefinition<string> LogMissingTable
            = new EventDefinition<string>(
                TaosEventId.MissingTableWarning,
                LogLevel.Warning,
                "TaosEventId.MissingTableWarning",
                LoggerMessage.Define<string>(
                    LogLevel.Warning,
                    TaosEventId.MissingTableWarning,
                    _resourceManager.GetString("LogMissingTable")));

        /// <summary>
        ///     For foreign key with identity {id} on table {tableName}, unable to find the column called {principalColumnName} on the foreign key's principal table, {principaltableName}. Skipping foreign key.
        /// </summary>
        public static readonly EventDefinition<string, string, string, string> LogPrincipalColumnNotFound
            = new EventDefinition<string, string, string, string>(
                TaosEventId.ForeignKeyPrincipalColumnMissingWarning,
                LogLevel.Warning,
                "TaosEventId.ForeignKeyPrincipalColumnMissingWarning",
                LoggerMessage.Define<string, string, string, string>(
                    LogLevel.Warning,
                    TaosEventId.ForeignKeyPrincipalColumnMissingWarning,
                    _resourceManager.GetString("LogPrincipalColumnNotFound")));

        /// <summary>
        ///     Found index with name: {indexName}, table: {tableName}, is unique: {isUnique}.
        /// </summary>
        public static readonly EventDefinition<string, string, bool?> LogFoundIndex
            = new EventDefinition<string, string, bool?>(
                TaosEventId.IndexFound,
                LogLevel.Debug,
                "TaosEventId.IndexFound",
                LoggerMessage.Define<string, string, bool?>(
                    LogLevel.Debug,
                    TaosEventId.IndexFound,
                    _resourceManager.GetString("LogFoundIndex")));

        /// <summary>
        ///     Found primary key with name: {primaryKeyName}, table: {tableName}.
        /// </summary>
        public static readonly EventDefinition<string, string> LogFoundPrimaryKey
            = new EventDefinition<string, string>(
                TaosEventId.PrimaryKeyFound,
                LogLevel.Debug,
                "TaosEventId.PrimaryKeyFound",
                LoggerMessage.Define<string, string>(
                    LogLevel.Debug,
                    TaosEventId.PrimaryKeyFound,
                    _resourceManager.GetString("LogFoundPrimaryKey")));

        /// <summary>
        ///     Found unique constraint with name: {uniqueConstraintName}, table: {tableName}.
        /// </summary>
        public static readonly EventDefinition<string, string> LogFoundUniqueConstraint
            = new EventDefinition<string, string>(
                TaosEventId.UniqueConstraintFound,
                LogLevel.Debug,
                "TaosEventId.UniqueConstraintFound",
                LoggerMessage.Define<string, string>(
                    LogLevel.Debug,
                    TaosEventId.UniqueConstraintFound,
                    _resourceManager.GetString("LogFoundUniqueConstraint")));

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}
