# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Run Example

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup TDengine
      uses: iotsharp/tdengine-action@master
      with:
        tdengine_version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x    
    - name: Restore dependencies
      run: dotnet restore EFCore.Taos.sln
    - name: Build
      run: dotnet build   -c Release --no-restore EFCore.Taos.sln        
    - name: Test
      run: dotnet run  -c Release --no-build  --no-restore --project src/Example/
